### ISSUE TITLE
Hidden input for textinput

### ISSUE THREAD

**Issue by kcbark** [charmbracelet/bubbles#10]
#### Feature request

Add option to hide input for sensitive strings such as passphrases or passwords. like type="password" in html.

**Comment by meowgorithm** [comment]
Just a note that @muesli just implemented this. To enable set the `EchoMode` property on the textinput model to `EchoPassword`. There’s also `EchoNone` to hide input entirely.

https://github.com/charmbracelet/bubbles/blob/master/textinput/textinput.go#L54
