### ISSUE TITLE
Missing function in README - Keys section

### ISSUE THREAD

**Issue by maxime-lair** [charmbracelet/bubbles#105]
Hello,

It seems there is missing functions calls in the code snippet for the [Keys section](https://github.com/charmbracelet/bubbles#key)

In the code snippet provided:
```
var DefaultKeyMap = KeyMap{
    Up: key.NewBinding(
        key.WithKeys("k", "up"),        // actual keybindings
        key.WithHelp("↑/k", "move up"), // corresponding help text
    ),
    Down: key.NewBinding(
        WithKeys("j", "down"),
        WithHelp("↓/j", "move down"),
    ),
}
```

On the ***Down*** element, `WithKeys` and `WithHelp` are not defined, It should be calling `key.WithKeys` and `key.WithHelp` instead

If this is intended, which one is considered correct?

Thanks

**Comment by muesli** [comment]
Thanks for spotting this! The former is correct: `key.WithKeys` & `key.WithHelp`.
