### ISSUE TITLE
Feature Request: Table

### ISSUE THREAD

**Issue by derricw** [charmbracelet/bubbles#109]
I am loving this project, but one thing that keeps me from replacing [tview](https://github.com/rivo/tview) is the lack of a table widget. It would be like a list widget but 2d and track cell selection.

**Comment by Evertras** [comment]
Hey, I ran into the same want and ended up writing one for myself here as a starting point: https://github.com/Evertras/bubble-table

**Comment by bashbunni** [comment]
This repo also has a great table layout https://github.com/dlvhdr/gh-dash

**Comment by wesleimp** [comment]
I’d like to implement this. @maaslalani could you help me if I need it.

**Comment by maaslalani** [comment]
@wesleimp Yep! For sure! Check out https://github.com/calyptia/go-bubble-table and https://github.com/Evertras/bubble-table for references. And, ping me on Slack (https://charm.sh/slack) if there's anything you need help with 😄

**Comment by maaslalani** [comment]
Table is now implemented thanks to @wesleimp 
 https://github.com/charmbracelet/bubbles/tree/master/table
