### ISSUE TITLE
[Docs] How to change color of the focused list item (title and description)?

### ISSUE THREAD

**Issue by koddr** [charmbracelet/bubbles#110]
Hi,

Can you tell me, how I can change the color of a list item (title and description) that is _currently_ in focus? 
I can't find it in the source code. 

![Screenshot 2022-01-30 at 15 28 12](https://user-images.githubusercontent.com/11155743/151699714-51d0d9fb-3974-41b1-9ce5-94bd7bebb8a8.png)

Can you please give me a hint? 😉

**Comment by meowgorithm** [comment]
Hi! Rendering (and behavior) for `list` items is done via the `ItemDelegate`. It can be a little confusing at first, but it allows the list to be very flexible and powerful.

If you just want to alter the default style you could do something like:

```go
import "github.com/charmbracelet/bubbles/list"

// Create a new default delegate
d := list.NewDefaultDelegate()

// Change colors
c := lipgloss.Color("#6f03fc")
d.Styles.SelectedTitle = d.Styles.SelectedTitle.Foreground(c).BorderLeftForeground(c)
d.Styles.SelectedDesc = d.Styles.SelectedTitle.Copy() // reuse the title style here

// Initailize the model with our delegate
m := model{list: list.New(items, d, 0, 0)}

// You can also change the delegate on the fly
m.list.SetDelegate(d)
```

For full control over the way list items are rendered you could define your own `ItemDelegate` too ([example](https://github.com/charmbracelet/bubbletea/blob/a6f46172ec4436991b90c2270253b2d212de7ef3/examples/list-simple/main.go#L28-L49)).

**Comment by zmnpl** [comment]
Ahh alright, thank you!
For me this is answered. list/defaultitem.go gives more insight (now that this understood :) ) about how the defaults styles are set up etc. 

Cheers!

**Comment by koddr** [comment]
OMG! Well, of course this is not done in the `list` style, but in the `item` style settings! 😞 It might be better to look in the source code, but if there is a way to specify it in the README (for everyone), that would be great.

Thanks, @meowgorithm
