### ISSUE TITLE
textinput: API to programmatically move cursor

### ISSUE THREAD

**Issue by antonmedv** [charmbracelet/bubbles#137]
I'd like to be able to see the system cursor in my app. 

Is it possible? Thanks.

**Comment by meowgorithm** [comment]
Small note to implementors: since there's no IO happening here this can just be done via methods on the model.

**Comment by maaslalani** [comment]
We now have a public `SetCursor` method to programatically move the cursor.

```
ti := textinput.New()
ti.Value = "Blah blah..."
ti.SetCursor(4)
```


https://github.com/charmbracelet/bubbles/blob/a4ed54327f08e510ec54408c93c2a08285c727af/textinput/textinput.go#L149-L154
