### ISSUE TITLE
In text inputs, with Konsole, Home/End/Del don't work

### ISSUE THREAD

**Issue by curio77** [charmbracelet/bubbles#14]
At least in Konsole/Linux, the <kbd>Home</kbd>/<kbd>End</kbd>/<kbd>Del</kbd> keys don't work inside text inputs.  <kbd>Del</kbd> creates opening brackets (`[`) that aren't counted in cursor movement, and the other two do nothing at all.

**Comment by curio77** [comment]
Thanks for the quick response, and sorry about misassigning the issue!

**Comment by meowgorithm** [comment]
Thanks again for reporting: this is now fixed in `master`. Turns out it also required a correction in Bubble Tea which is now fixed in a point release at `v0.12.1`. We'll do a release on Bubbles shortly, too.
