### ISSUE TITLE
KeySpace KeyType is not handled

### ISSUE THREAD

**Issue by rosmanov** [charmbracelet/bubbles#144]
bubbletea has recently [changed](https://github.com/charmbracelet/bubbletea/commit/14e58aa1f92fa9bd756d9e739ce63a39e98a39ac) the KeyType for the space character.

As a result, in particular, nothing happens when the user enters space in the `textinput` component.

We need to add a `case tea.KeySpace:` somewhere around [these lines](https://github.com/charmbracelet/bubbles/blob/292a1dd7ba97b1dc96a12d5ba50301cc731ef37f/textinput/textinput.go#L632-L652).

----

bubbles revision is `292a1dd7ba97b1dc96a12d5ba50301cc731ef37f` (current `master`)

**Comment by meowgorithm** [comment]
Hi! @bashbunni just fixed this in https://github.com/charmbracelet/bubbletea/pull/289. It will be available in the next release of Bubble Tea. If you need the functionality immediately you can pin to `master`.

Sorry for the confusion!

**Comment by meowgorithm** [comment]
Oh wait

**Comment by bashbunni** [comment]
@meowgorithm let me know if this is still a wip but saw it was merged

**Comment by meowgorithm** [comment]
Merged in `master` on the Bubble Tea side. Let’s get this one in a PR and queue it up to be merged right after the next Bubble Tea release.

**Comment by meowgorithm** [comment]
This is now fixed for both the present and the upcoming Bubble Tea versions.
