### ISSUE TITLE
Multi-line spinners

### ISSUE THREAD

**Issue by chelnak** [charmbracelet/bubbles#165]
Hello! 

When using a worker pool pattern (or similar) you might want to display spinners for for each task, each one updating as the respective task state changes. 

Is this something that is possible with the spinner today and if not is it something that you would support in the future?

Thank you!

**Comment by meowgorithm** [comment]
Yep! By default spinners will only respond to their own messages, so it’s safe to flow all messages through all spinners and have normal behavior.

**Comment by chelnak** [comment]
Oh awesome! Thanks for the response!
