### ISSUE TITLE
list support mouse click event

### ISSUE THREAD

**Issue by liulhdarks** [charmbracelet/bubbles#175]
How does it determine which line of the list the mouse is in? I need to list support mouse click event.

**Comment by gabe565** [comment]
I also needed this and came across [lrstanley/bubblezone](https://github.com/lrstanley/bubblezone). I'm using it in a few lists now without issue! The repo even has an example with a list.

**Comment by maaslalani** [comment]
+1 for [lrstanley/bubblezone](https://github.com/lrstanley/bubblezone), it works great!
