### ISSUE TITLE
Timer component

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [charmbracelet/bubbles#22]
👋🏽 hi, awesome work on the whole bubbletea framework!

### What
I was wondering what would be the `tea`  semantic way to incorporate a timer into a tea application. I want the app to display the time that is left and for the it to exit gracefully once the timer is done. 

I looked under the hood of the Spinner, given that it ticks at at regular interval, as a base for a ticker component. I spotted the [`tea.Tick`](https://github.com/charmbracelet/bubbletea/blob/9e9e05774cb6583783fad87ea73f8e0b696bd75c/commands.go#L48) function which looks promising.

**Comment by meowgorithm** [comment]
Yep, you’re exactly right: `tea.Tick` is what you’re looking for. I just added [a countdown example](https://github.com/charmbracelet/bubbletea/blob/master/examples/countdown/main.go) to illustrate your use case. There are lots of other ways you could model this, too.

If you wanted to synchronize the timer with the system clock you could also use [`tea.Every`](https://pkg.go.dev/github.com/charmbracelet/bubbletea#Every).

Thanks for the kind words about Bubble Tea!

**Comment by meowgorithm** [comment]
Reopening this, actually, as a timer component may make sense for the library.
