### ISSUE TITLE
does not contain package github.com/charmbracelet/bubbles/table

### ISSUE THREAD

**Issue by TXYan** [charmbracelet/bubbles#224]
the lastest version(v0.13.0) does not contain package github.com/charmbracelet/bubbles/table

**Comment by Likhi** [comment]
If I fork master, run 'go mod tidy' (resulting change is from CRLF to LF line separators) and then import my forked github.com/Likhi/bubbles/table, it seems resolve the 'table' import without the issue noted above.

**Comment by meowgorithm** [comment]
Yeah, `table` is currently in `master` and not part of a release yet. For the moment you can:

```
go get github.com/charmbracelet/bubbles@master
```

**Comment by maaslalani** [comment]
Should be included in the latest release [v0.14.0](https://github.com/charmbracelet/bubbles/releases/tag/v0.14.0)
