### ISSUE TITLE
list: Broken rendering when Height set to window size

### ISSUE THREAD

**Issue by ktprograms** [charmbracelet/bubbles#238]
When applying this diff to [list-simple/main.go](https://github.com/charmbracelet/bubbletea/tree/master/examples/list-simple/main.go), the rendering is broken when pressing down/j (the lines above become invisible):

```diff
diff --git a/examples/list-simple/main.go b/examples/list-simple/main.go
index 97628db..807e107 100644
--- a/examples/list-simple/main.go
+++ b/examples/list-simple/main.go
@@ -63,6 +63,7 @@ func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
 	switch msg := msg.(type) {
 	case tea.WindowSizeMsg:
 		m.list.SetWidth(msg.Width)
+		m.list.SetHeight(msg.Height)
 		return m, nil
 
 	case tea.KeyMsg:
```

Changing it to `msg.Height-1` works, though, and the list looks the same before input (one blank line above title and below help bar).

**Comment by muesli** [comment]
You can't give the list the full height as you need to account for other UI components taking up vertical space.

**Comment by ktprograms** [comment]
Ah, just noticed there's an additional `\n` being printed. That explains it, thanks.
