### ISSUE TITLE
Cursor jumps to the end of line after typing one character at the beginning of input

### ISSUE THREAD

**Issue by noahgorstein** [charmbracelet/bubbles#249]
Reported to me originally here: https://github.com/noahgorstein/jqp/issues/9

I reproduced using the [textinput example](https://github.com/charmbracelet/bubbletea/tree/master/examples/textinput).

Steps to reproduce with example:
- type something into input
- Press `Ctrl+a`
- Start typing again, the cursor should have moved to the end of what you previously typed

Wondering also if there is a workaround for this issue for now.

**Comment by noahgorstein** [comment]
this is not an issue with the current `master`. Going to close this as it appears to be fixed.

**Comment by maaslalani** [comment]
Thanks for the issue @noahgorstein. In case you're interested, here was the fix: https://github.com/charmbracelet/bubbles/commit/9e2d21482fab5afda3f4f4895cfb20b0b636e442
