### ISSUE TITLE
Why is the animated progress bar not smooth in my terminal 

### ISSUE THREAD

**Issue by rew1nter** [charmbracelet/bubbles#292]
![Screenshot_2022-11-14-01-15-56-967-edit_com google android apps cloudconsole](https://user-images.githubusercontent.com/64508791/201539980-b3f232fe-c441-45d5-b06d-dd07bf7fd745.jpg)
This is what it looks like. The GIF in repo looks way nicer compared to this. What's the workaround here?

**Comment by muesli** [comment]
This example uses 24-bit RGB colors and it looks like your terminal doesn't support that, so it uses the closest available colors. Which terminal are you using?

**Comment by rew1nter** [comment]
I'm using Alacritty and the TERM is set to `xterm-256color`.

**Comment by rew1nter** [comment]
Okay I found the problem. tmux doesn't have true colours enabled. It shows the true colours in alacritty when I run this outside tmux.

**Comment by dlvhdr** [comment]
You can set these options in your `tmux.conf` to enable them:
```
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"
setenv -g COLORTERM truecolor
```
