### ISSUE TITLE
table border styling

### ISSUE THREAD

**Issue by tredeske** [charmbracelet/bubbles#299]
There does not appear to be a way to style the border of the table.  I tried styling the header, but that only affected the border under the header.

**Comment by Hurka5** [comment]
There is a way to style it just take a look at the example: 
https://github.com/charmbracelet/bubbletea/blob/master/examples/table/main.go
```
...
var baseStyle = lipgloss.NewStyle().
	BorderStyle(lipgloss.NormalBorder()).
	BorderForeground(lipgloss.Color("240"))
...
func (m model) View() string {
	return baseStyle.Render(m.table.View()) + "\n"
}
...

```

**Comment by tredeske** [comment]
That is what I tried before putting in the ticket.  It had no effect on the border around the table - only on the line under the table header.

**Comment by tredeske** [comment]
```
border := libgloss.NormalBorder()
border.Top = "+"
style := lipgloss.NewStyle().BorderStyle(border). ...

...
// in view:
style.Render(table.View())

```

The top border remains the same.

**Comment by tredeske** [comment]
With the above help, I was able to get this to work!
