### ISSUE TITLE
textinput: Prompt length not taken into account for width

### ISSUE THREAD

**Issue by mikelorant** [charmbracelet/bubbles#307]
When creating a textinput, the prompt width is added to the width of the entire textinput. This means that two text inputs with a width of 20, will have different lengths based on the length of the prompt. This is visible when adding a border.

```
func initialModel() model {
	tiA := makeTextInput("1234")
	tiB := makeTextInput("1234567890")

	return model{
		textInputA: tiA,
		textInputB: tiB,
	}
}

func makeTextInput(str string) textinput.Model {
	ti := textinput.New()
	ti.Prompt = str
	ti.Focus()
	ti.CharLimit = 156
	ti.Width = 20

	return ti
}
```

![](https://d.pr/i/0R02PO.png)

I have an example of this bug here:
https://github.com/mikelorant/bubbles-textinput-prompt

Looking at the textinput code, it is clear that the prompt length is never subtracted from the width. I believe the width is actually shorter than it should be but I am unclear what the intended width is meant to represent.

**Comment by mikelorant** [comment]
@meowgorithm Can we get some clarification of what the width is meant to mean. You were the last person to touch this field so I am hoping you know the reasons behind why 😄 

```
// Width is the maximum number of characters that can be displayed at once.
// It essentially treats the text field like a horizontally scrolling
// viewport. If 0 or less this setting is ignored.
Width int
```
https://github.com/charmbracelet/bubbles/blob/master/textinput/textinput.go#L113-L116

I have two possible interpretations:
1. The width is the entire `textinput` component.
2. The width is just the visible area for user input space. Promps and extra padding ADD to this width.

Whatever the answer is, I believe we should update the documentation clarifying this field. If there is a bug, I will put up the appropriate pull request to fix this.

**Comment by meowgorithm** [comment]
Okay, jumping back in on this one: `Width` here is the width of the `textinput` input area only — so not including margins, borders, padding and so on.

**Comment by mikelorant** [comment]
@meowgorithm Thanks for the clarification. Will close this issue as it seems everything is working as expected.

**Comment by mikelorant** [comment]
@meowgorithm Thanks for the clarification. Will close this issue as it seems everything is working as expected.

**Comment by mikelorant** [comment]
@meowgorithm Thanks for the clarification. Will close this issue as it seems everything is working as expected.
