### ISSUE TITLE
Viewport.SetContent() Timing Question

### ISSUE THREAD

**Issue by asutula** [charmbracelet/bubbles#35]
I'm playing with the [pager example](https://github.com/charmbracelet/bubbletea/blob/master/examples/pager/main.go) over in the Bubbletea repo. I noticed the call:
```
m.viewport.SetContent(m.content)
```
appears in the `Update` func. Doing this sort of side effect in `Update` seems odd to me, so I tried moving it to `View`, but in that case, the viewport stops responding to input. I'm not sure `View` is any better of a place to call `SetContent`, but I just want to understand what is going in here and if updating the viewport content in `Update` is _the_ way to go always.

Thanks!

**Comment by asutula** [comment]
Hmm now that I think about it, `viewport` is actually a model (not a "view"), so I guess it does make sense to update it's content in `Update`, just as you would any other model information. Pretty sure I answered my own question here, but will leave this open in case there is something I'm missing. Feel free to confirm and close.

**Comment by meowgorithm** [comment]
Yep, precisely. You update the viewport with `viewport.Model.SetContent` and then render it with `viewport.Model.View`.

[`SetContent`](https://github.com/charmbracelet/bubbles/blob/master/viewport/viewport.go#L69) is essentially a setter for an internal variable on the model where we perform some operations on the input (namely, break it into lines) so we can render the relevant parts with `viewport.Model.View()`.

**Comment by asutula** [comment]
Perfect, thanks.
