### ISSUE TITLE
`textinput.BackgroundStyle` doesn't do anything

### ISSUE THREAD

**Issue by mieubrisse** [charmbracelet/bubbles#360]
It looks like `BackgroundStyle` was replaced with `TextStyle` since `TextStyle` is what's used in `textinput.Model.View`

**Comment by bashbunni** [comment]
Hey @mieubrisse this was removed already on `master`, looks like it has just been a while since our last Bubbles release. I'll make note of that and see about getting a new release out soon :) 

Related: https://github.com/charmbracelet/bubbles/pull/341
