### ISSUE TITLE
'textinput.CursorStyle' does nothing

### ISSUE THREAD

**Issue by usrme** [charmbracelet/bubbles#364]
After commit https://github.com/charmbracelet/bubbles/commit/a99b55cda1e062bda795b8b6065be4dd8901dffe in between releases https://github.com/charmbracelet/bubbles/compare/v0.14.0...v0.15.0 it seems that applying a style to directly to the `CursorStyle` field does nothing.

In my own code I had to make the following change to get the style that previously applied fine to be applied again:

```diff
diff --git a/gui.go b/gui.go
index 853e1a8..57830ba 100644
--- a/gui.go
+++ b/gui.go
@@ -121,7 +121,7 @@ func newModel(items, sortedItems []list.Item, path string) 
        hostList.Styles.Title = titleStyle
        hostList.FilterInput.PromptStyle = filterPromptStyle
-       hostList.FilterInput.CursorStyle = filterCursorStyle
+       hostList.FilterInput.Cursor.Style = filterCursorStyle
 
        // Make sure custom keys have help text available
        hostList.AdditionalShortHelpKeys = func() []key.Binding {
@@ -141,7 +141,7 @@ func newModel(items, sortedItems []list.Item, path string) model {
        input := textinput.New()
        input.Prompt = "Connect to: "
        input.PromptStyle = inputPromptStyle
-       input.CursorStyle = inputCursorStyle
+       input.Cursor.Style = inputCursorStyle
 
        sp := spinner.New()
        sp.Spinner = spinner.Pulse
```

I'm not well versed in Go, so it's very likely that I'm misunderstanding something and should just refactor in an entirely different way.

**Comment by maaslalani** [comment]
Hey! Apologies for the confusion, you should definitely use `Cursor.Style` for the future as `CursorStyle` is no longer used. I will deprecate that field now!

**Comment by usrme** [comment]
@maaslalani, thanks for the quick reply and for all the wonderful work you've done!
