### ISSUE TITLE
Feature Request: Add File Picker

### ISSUE THREAD

**Issue by mahadevans87** [charmbracelet/bubbles#37]
Is it possible to create a File Picker Bubble that could be easily used?

I would imagine a cursor and selection that could be moved around using arrow keys and a tree like view for files/folders

**Comment by quenbyako** [comment]
@mahadevans87 sounds great, could you please visualise your idea or sort of? i mean, in ascii graphics :smile:

**Comment by mahadevans87** [comment]
@quenbyako Is it possible to build something like this?

![image](https://user-images.githubusercontent.com/1255523/104799223-5d5d5800-57f3-11eb-94b8-7454de611b71.png)

Source : https://github.com/jarun/nnn

**Comment by meowgorithm** [comment]
Yeah, it's very possible to build something like that with Bubble Tea. I'd put the file listing in a viewport component so it can scroll.

[Modu](https://github.com/KimMachineGun/modu) is a good reference on how to do implement something like that from a UI standpoint.

We're big fans of nnn, btw.

**Comment by quenbyako** [comment]
@meowgorithm @mahadevans87  quick ask: does go has some package that you know, which is providing icon utilities or any font stuff, which we can use?

i've created already file toolbox and ls-alternative looks like this result on you screenshot:
![image](https://user-images.githubusercontent.com/13191308/104853837-80335d80-5914-11eb-8313-5327424cb75e.png)


It's looks **not sooooo** cool looking, but it might be a goof start point on working with this feature.

Also, it's off topic generally, but i working on cli argument parser, this `filetools` project use it, i want to make typical project structure, which can be used as template for any cli app. But it's really off topic, i just want warn you about a lot of problems with this toolbox, if i'll opensource it

**Comment by mrusme** [comment]
I'm in need for a file picker as well and I came across this issue. I'm wondering whether it makes sense to **actually** build a file picker from scratch or instead integrate something that supports running arbitary commands, display their output within a specified area while the command runs and then read a temporary file after the command has exited. It would also need to forward input to the command for as long as the command is still running.

With this generic implementation users could run *any* terminal file manager they're comfortable with (e.g. [`lf -selection-path /tmp/bla`](https://github.com/gokcehan/lf/issues/89), `nnn -p -`, `ranger something something`, ...) and the bubble wouldn't actually need to implement all the logic that usually goes into a good file manager. It could offer some *presets* for popular file managers like lf, nnn, ranger, mc, etc.

The flow would be:

- Render a "Select file ..." button somewhere that would activate the *file picker* bubble (this doesn't have to be part of the implementation though as button interactions haven't yet been clearly specififed by Bubble Tea)
- Display the *virtual terminal* bubble area that outputs the command's stdout and forward all stdin to the command, until the command has quit
- Run the command with a temporary file for outputting the selected file(s), e.g. `lf -selection-path /tmp/bla`
- Wait for the command to quit, then read `/tmp/bla` and provide its content as `[]string` via a `.Value()` function on the `Model`.

Wdyt?

**Comment by mrusme** [comment]
FYI because I just stumbled upon this: 

It seems part of an file picker is already available through [teacup](https://github.com/knipferrc/teacup/tree/main/filetree).

**Comment by KaiAragaki** [comment]
Was this closed in https://github.com/charmbracelet/bubbles/pull/343?

**Comment by maaslalani** [comment]
Yes thank you! File picker bubble was added in #343!
