### ISSUE TITLE
go get fails with 'Model does not implement tea.Model (missing Init method)'

### ISSUE THREAD

**Issue by fedragon** [charmbracelet/bubbles#4]
Hello,

I'm unable to `get` this library due to the following error: 

```
go get github.com/charmbracelet/bubbles/textinput
# github.com/charmbracelet/bubbles/textinput
../../go/pkg/mod/github.com/charmbracelet/bubbles@v0.6.1/textinput/textinput.go:400:16: impossible type assertion:
        Model does not implement tea.Model (missing Init method)
```

I've also tried getting other versions (6.0.0, 5.0.1) but they all return the same error.

**Comment by meowgorithm** [comment]
So sorry about that and thank you for flagging this. I just pushed `v0.7.0` which fixes this. Let us know if anything else seems awry!

**Comment by fedragon** [comment]
No problem at all, it now works fine!
