### ISSUE TITLE
Add option for textinput to wrap text instead of scrolling horizontally

### ISSUE THREAD

**Issue by cpendery** [charmbracelet/bubbles#417]
**Is your feature request related to a problem? Please describe.**
I need to have user input wrap so it's all visible on screen instead of wrapping as if a horizontally scrolling viewport

**Describe the solution you'd like**
Add a `Wrap` bool field to the `textinput` Model struct that when set wraps text to the width of the screen

**Describe alternatives you've considered**
N/A, I'd like to use the features in `textinput`, but I need wrapping support

**Additional context**

**Comment by meowgorithm** [comment]
If you need wrapping, why not use [`textarea`](https://github.com/charmbracelet/bubbles#text-area)?

**Comment by cpendery** [comment]
Closing as resolved as I didn't know you could remove line numbers from `textarea`
