### ISSUE TITLE
Optimize Textarea’s `wrap()`

### ISSUE THREAD

**Issue by meowgorithm** [charmbracelet/bubbles#456]
As discussed in https://github.com/charmbracelet/bubbletea/issues/831#issuecomment-1763551383, let's memoize Textarea's `Wrap()` function to improve performance.

**Comment by mikelorant** [comment]
Can we please get #427 merged as this provides immediate benefits to the performance of `textarea`.

I believe combing this with the replacing `runewidth.StringWidth` with `uniseg.StringWidth` should give us a giant bump in performance such that there will be far less complaints about performance with this component.

**Comment by meowgorithm** [comment]
Agreed — we should generally switch to `uniseg.StringWidth`; should also happen in https://github.com/muesli/termenv upstream.
