### ISSUE TITLE
Text Input cursorEnd doesn't work as expected

### ISSUE THREAD

**Issue by cakir-enes** [charmbracelet/bubbles#49]
Hello,
```go
m.textInput.SetValue(fmt.Sprintf("%s |a word|", m.textInput.Value()))
m.textInput.CursorEnd() // sets cursor on last character, so next input goes _before_ last character 
```
Couldn't use `setCursor(pos)` as workaround due to imp of it.

Also why `pos` is private? I need to find if the cursor is inside a `|` block. Is there a way to achieve this without accessing `pos`?

**Comment by meowgorithm** [comment]
Hi! `SetCursor()` is working fine on on my end. Are you sure you're using the latest version of Bubbles? Here's the code I used to verify:

https://gist.github.com/meowgorithm/4bcc23c0505a5ce0981d12abf9cd291c

And that's a good point about the position: it most likely makes sense to expose some sort of access to it.

**Comment by cakir-enes** [comment]
I was also calling `m.input, cmd = m.input.Update..`, after I removed that it worked fine thanks for the example.

Unrelated but is multiline text inputs coming soon? Having multiple textinputs to simulate it could work until people try to paste things, I assume.
