### ISSUE TITLE
Avoid breaking change in patch versions

### ISSUE THREAD

**Issue by reenjii** [charmbracelet/bubbles#51]
Hi,

You broke your own tool glow by introducing a breaking change in a patch version.

See https://github.com/charmbracelet/glow/issues/268

See documentation for correctly using semver. https://golang.org/ref/mod#versions

Hope it helps, gook luck :)

**Comment by muesli** [comment]
Thank you. Response on https://github.com/charmbracelet/glow/issues/268.

**Comment by muesli** [comment]
We will add a notice/reminder to our READMEs that our releases <v1.0.0 aren't strictly semver-compliant.
