### ISSUE TITLE
Feat/pull: Disable cursor blinking in textinput. 

### ISSUE THREAD

**Issue by abyxcos** [charmbracelet/bubbles#53]
I would like to disable the blinking cursor in the textinput widget. It looks like all the parts are there to do it, but none of them are exposed. I'm willing to send a pull request for this, but I'm not sure what the best way to go about this would be, so I wanted to ask first. 

Tentatively wrapping the two calls to m.blinkCmd() in Update() seems like the quickest way, but I'm not sure if you wanted to expand the class to allow for a better way to set this, maybe by promoting Model.cursorMode and respecting it's state.

**Comment by meowgorithm** [comment]
Yeah, you're totally right: we started implementing a static cursor but never exposed anything as we didn't finish the implementation. If you don't mind, let me take a look quickly. The cursor blink stuff is rather nuanced, but it may not be too much effort to get a static cursor working as you suggest.

**Comment by meowgorithm** [comment]
@abyxcos Ok! This is now in `master` and will be available in the next release. You can set a static cursor with something like the following:

```go
m := textinput.NewModel()
m.SetCursorMode(textinput.CursorStatic)
```

**Comment by abyxcos** [comment]
Thanks, working great.
