### ISSUE TITLE
JoinHorizontal should use top/bottom not left/right

### ISSUE THREAD

**Issue by shaunco** [charmbracelet/bubbles#553]
These `JoinHorizontal` calls should use `lipgloss.Top` rather than `lipgloss.Left`:
- https://github.com/charmbracelet/bubbles/blob/64a67d167062e075d80a132afc0851fd1b2c6b89/table/table.go#L421
- https://github.com/charmbracelet/bubbles/blob/64a67d167062e075d80a132afc0851fd1b2c6b89/table/table.go#L445

**Comment by aditipatelpro** [comment]
@shaunco , I would love to contribute to this project and this issue seems interesting to start with. 
I would love to start working on this if you are open for contributions.

**Comment by shaunco** [comment]
@aditipatelpro I am just a user of charmbracelet, not a maintainer but it appears that the project accepts plenty of outside PRs.

**Comment by aditipatelpro** [comment]
Thank you @shaunco.

@muesli @meowgorithm @aymanbagabas, I am interested in contributing to this project and would love to start working on it if you are open to it.

**Comment by bashbunni** [comment]
@aditipatelpro if you would like to contribute a fix for this, please do! We appreciate all of the contributions we get :)
