### ISSUE TITLE
Multiline Textinput

### ISSUE THREAD

**Issue by laxman20** [charmbracelet/bubbles#63]
I want to use the text input bubble to allow the user to enter some notes. They can enter newlines in the notes if they want. It looks like the text input component ignores the Enter key event. Is it possible to add multi-line support so that <Enter> gets translated to "\n"? Or is there a more appropriate component for this?

**Comment by LeonB** [comment]
Any news on this? Just curious!

**Comment by meowgorithm** [comment]
I'm pleased to report this feature is now in development.

**Comment by maaslalani** [comment]
@LeonB @laxman20 

`textarea` bubble is now merged into `master` and will be included in the next release! Excited to see what you all build :)

https://github.com/charmbracelet/bubbles

**Comment by maaslalani** [comment]
There are some examples on how to use it here: https://github.com/charmbracelet/bubbletea/pull/357

**Comment by LeonB** [comment]
@maaslalani thanks! Going to check it out!
