### ISSUE TITLE
`textinput.Model` doesn't seem to work well with append.

### ISSUE THREAD

**Issue by rentruewang** [charmbracelet/bubbles#65]
When storing multiple `textinput.Model`s in a slice, like in the official example [`textinputs`](https://github.com/charmbracelet/bubbletea/blob/master/examples/textinputs).

If we update the [`Update`](https://github.com/charmbracelet/bubbletea/blob/3930519979014a10d06c3f78cd1589c8e7a0fb72/examples/textinputs/main.go#L69) function like so:

```diff
func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "ctrl+c", "esc":
			return m, tea.Quit

		// Change cursor mode
		case "ctrl+r":
			m.cursorMode++
			if m.cursorMode > textinput.CursorHide {
				m.cursorMode = textinput.CursorBlink
			}
			cmds := make([]tea.Cmd, len(m.inputs))
			for i := range m.inputs {
				cmds[i] = m.inputs[i].SetCursorMode(m.cursorMode)
			}
			return m, tea.Batch(cmds...)

+ 		case "ctrl+q":
+ 			before := m.inputs[:m.focusIndex]
+ 			after := m.inputs[m.focusIndex:]
+ 			line := textinput.NewModel()
+ 
+ 			before = append(before, line)
+ 			before = append(before, after...)
+ 			m.inputs = before

		// Set focus to next input
		case "tab", "shift+tab", "enter", "up", "down":
			s := msg.String()

			// Did the user press enter while the submit button was focused?
			// If so, exit.
			if s == "enter" && m.focusIndex == len(m.inputs) {
				return m, tea.Quit
			}

			// Cycle indexes
			if s == "up" || s == "shift+tab" {
				m.focusIndex--
			} else {
				m.focusIndex++
			}

			if m.focusIndex > len(m.inputs) {
				m.focusIndex = 0
			} else if m.focusIndex < 0 {
				m.focusIndex = len(m.inputs)
			}

			cmds := make([]tea.Cmd, len(m.inputs))
			for i := 0; i <= len(m.inputs)-1; i++ {
				if i == m.focusIndex {
					// Set focused state
					cmds[i] = m.inputs[i].Focus()
					m.inputs[i].PromptStyle = focusedStyle
					m.inputs[i].TextStyle = focusedStyle
					continue
				}
				// Remove focused state
				m.inputs[i].Blur()
				m.inputs[i].PromptStyle = noStyle
				m.inputs[i].TextStyle = noStyle
			}

			return m, tea.Batch(cmds...)
		}
	}

	// Handle character input and blinking
	cmd := m.updateInputs(msg)

	return m, cmd
}

```

After pressing `ctrl+q`, two lines are blanked.

Before:
![2021-09-02-03-43-21](https://user-images.githubusercontent.com/32859905/131734173-2719ca91-acc5-4a19-b25f-586a3ab2a318.png)
After:
![2021-09-02-03-43-53](https://user-images.githubusercontent.com/32859905/131734198-b95c6bc5-3c39-496f-b0b2-7c7f3770d0ba.png)

Thanks for reading this!

**Comment by meowgorithm** [comment]
Hi! You actually just need to `copy` the slice to avoid mutating it (since slices are pointers to arrays). There are a few ways to do this, here's one example:

```go
case "ctrl+q":
	m.inputs = append(m.inputs, textinput.Model{})           // increase the size of the slice by 1
	copy(m.inputs[m.focusIndex+1:], m.inputs[m.focusIndex:]) // shift the tail of the slice by 1
	m.inputs[m.focusIndex] = textinput.NewModel()            // insert a new textinput
```

**Comment by rentruewang** [comment]
Hi, thanks for the reply! The solution works, that's super helpful!
I'm not sure how I mutated the models by appending some models to the tail of an existing slice, AFAIK, `append` only copies the structures that's passed in by value, so it shouldn't really modify anything. Do you mind pointing out where mutation happends?

**Comment by meowgorithm** [comment]
This isn't specific to `textinput.Model`. Rather, it's how slices work internally in Go. The arguments to `append` are indeed being passed by value, however slices are just structures that contain pointers to an underlying array. Internally Go represents slices more or less like this:

```go
var underlyingArray [3]string

slice := struct{
    Length:        3,
    ZerothElement: &underlyingArray[0],
}
```

So if you slice that slice with `slice := slice[1:]` the representation becomes:

```go
slice := struct{
    Length:        2,
    ZerothElement: &underlyingArray[1],
}
```

So in the case above, when you append to `before` you're inserting an element into the same underlying array that `after` is referencing. This causes `after` to suddenly be pointing to the wrong position in its underlying array, which happens to be the element that was just appended to `before` ([example](https://play.golang.org/p/y0n3jv7tnYg)). Because of this, you need to use `copy` to create a new underlying array for `after`:

```go
slice := []string{"a", "b", "c"}
index := 1

before := slice[:index]

// Copy the tail into a new slice so that it contains a separate underlying array.
after := make([]string, len(slice[index:]))
copy(after, slice[index:])

// Now you can safely append an element to the head and concatenate the two slices.
before = append(before, "NEW")
slice = append(before, after...)
fmt.Printf("%#v\n", slice)
```

([Playground](https://play.golang.org/p/KJa2EfEU6Sn))

I highly recommend reading [Rob Pike's excellent blog post](https://go.dev/blog/slices) on how `append` work internally. It’s really good.

**Comment by rentruewang** [comment]
Oh wow! Thanks for your in depth explanation. Really appreciate it!
