### ISSUE TITLE
Starting stopwatch multiple times increases speed

### ISSUE THREAD

**Issue by ipsavitsky** [charmbracelet/bubbles#661]
**Describe the bug**
When applying multiple stopwatch.Start commands, stopwatch starts ticking faster with each one.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS Ubuntu
 - Shell bash
 - Terminal Emulator kitty
 - Terminal Multiplexer zellij
 - Locale en_US.UTF-8

**To Reproduce**
1. Compile code
2. Run program
3. Press enter a couple times, sending a Start command with each one

**Source Code**
```go
package main

import (
	"log"

	"github.com/charmbracelet/bubbles/stopwatch"
	tea "github.com/charmbracelet/bubbletea"
)

func main() {
	p := tea.NewProgram(initialModel())

	if _, err := p.Run(); err != nil {
		log.Fatal(err)
	}
}

type model struct {
	stopwatch stopwatch.Model
}

func initialModel() model {
	return model{
		stopwatch: stopwatch.New(),
	}
}

func (m model) Init() tea.Cmd {
	return nil
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	var cmds []tea.Cmd
	var cmd tea.Cmd

	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.Type {
		case tea.KeyEnter:
			cmds = append(cmds, m.stopwatch.Start())
		case tea.KeyCtrlC:
			return m, tea.Quit
		}
	}

	m.stopwatch, cmd = m.stopwatch.Update(msg)
	cmds = append(cmds, cmd)
	return m, tea.Batch(cmds...)
}

func (m model) View() string {
	return m.stopwatch.View()
}
```

**Expected behavior**
Stopwatch starts with the first press of enter and keeps running at expected speed with every subsequent Start message

**Screenshots**
![demo](https://github.com/user-attachments/assets/9bde004a-b443-41aa-a3f6-e6b6256dd01a)

**Additional context**
The vhs tape for the above gif is
```
Output demo.gif

Show

Type ./bubbles_bugreport

Enter

Sleep 3s

Enter
Enter
Enter
Enter

Sleep 10
```

Somehow, the `TickMsg` get stacked with every Start() call

**Comment by meowgorithm** [comment]
Good catch: this should be an easy fix.

**Comment by meowgorithm** [comment]
Hey again. This should be fixed on `master` now. If we've made a mistake and it's not fixed, please reopen this issue.

Thanks for flagging this bug!
