### ISSUE TITLE
viewport: lazy loading

### ISSUE THREAD

**Issue by flavono123** [charmbracelet/bubbles#694]
**Is your feature request related to a problem? Please describe.**
when i render over a 10k lines of string, updating is lagging with a low responsive

**Describe the solution you'd like**
only render the set content then lazy load for others, the out of current content

**Describe alternatives you've considered**
idk

**Additional context**
will attach simple codes to reproduce soon

**Comment by meowgorithm** [comment]
Hey @flavono123! This is a good one, thanks for filing an issue against it.

Please do include some sample code when you can: it will make it a lot easier for us to look into this one (a [gist](https://gist.github.com) is fine if you need to include a large amount of data).

**Comment by flavono123** [comment]
hello @meowgorithm 

first, my assumption was wrong. just only 10k lines of string do not occur lags to bubbletea's rending lifecycle.
as you said it might be related retrieving some amount of data.
i observed this issue in my personal project, which is not distributed yet, so tricky to explain to reproduce i could if you want.

you may close this issue is not urgent.

**Comment by meowgorithm** [comment]
Sounds good. If this does become a problem for you don't hesitate to reopen.

**Comment by flavono123** [comment]
https://github.com/flavono123/kupid?tab=readme-ov-file#limitation

fyi. this is the use case, not friendly reproducing instructions.
