### ISSUE TITLE
viewport: last line of content not rendered when scrolling if it doesn't end with new line `\n`

### ISSUE THREAD

**Issue by MarcoLucidi01** [charmbracelet/bubbles#73]
hello, I come from a project ([`ticker`][1]) that uses `bubbles/viewport` to display its main contents.

we noticed that when the content doesn't fit on a single page and you scroll at the bottom, `bubbles/viewport` doesn't render the last line of content **if** it doesn't end with a new line `\n` character ([here the issue #158 reported on `ticker`][2]).

the problem is reproducible with [`bubbletea`'s pager example][3] that uses `bubbles/viewport`, for example:

    $ git clone https://github.com/charmbracelet/bubbletea.git
    ...
    $ cd bubbletea/examples/pager/
    $ go build
    $ ls -1
    artichoke.md    # file displayed in the example
    main.go
    pager*
    $ tail -1 artichoke.md | xxd | tail -1
    00000030: 2069 6e20 5370 616e 6973 682e 0a          in Spanish..    # ends with new line
    $ ./pager

https://user-images.githubusercontent.com/23704923/133423929-6b4b7251-8abe-44b5-b040-b663e53f63bf.mp4

everything looks fine, now I remove last new line `\n` character from `artichoke.md`:

    $ truncate -s -1 artichoke.md
    $ tail -1 artichoke.md | xxd | tail -1
    00000030: 2069 6e20 5370 616e 6973 682e             in Spanish.
    $ ./pager

https://user-images.githubusercontent.com/23704923/133424155-3faf68e6-2604-4019-b3ba-8b194e5a7435.mp4

and the last line

    _Alcachofa_, if you were wondering, is artichoke in Spanish.

is not displayed anymore.

unfortunately I don't have a patch, I suspect it's an off-by-one error because I see lots of `len(m.lines)-1` in `viewport.go` and I think it could be related to the problem, but I wasn't able to completely figure it out.

[1]: https://github.com/achannarasappa/ticker
[2]: https://github.com/achannarasappa/ticker/issues/158
[3]: https://github.com/charmbracelet/bubbletea/tree/master/examples/pager

**Comment by meowgorithm** [comment]
Noted, thanks for the report. I suspect you’re right about the off-by-one error, but we’ll take a look.

**Comment by meowgorithm** [comment]
This is now fixed in `master` and will be available in the next release. Thank you very much for the thorough report!
