### ISSUE TITLE
Extraspace on Dot spinner

### ISSUE THREAD

**Issue by ValentinTrinque** [charmbracelet/bubbles#75]
I think we have an unwanted extra space on the Dot spinner, here:

https://github.com/charmbracelet/bubbles/blob/0ac5ecdf8170df53c057b079cca315ac77c31d16/spinner/spinner.go#L25

Is this intended ?

If not, I can submit a PR.

**Comment by bashbunni** [comment]
Hey @ValentinTrinque 

I do believe that is intentional. Thank you though!
