### ISSUE TITLE
List Widget: Disabling Help or Quit Undone When Exiting Filter

### ISSUE THREAD

**Issue by ibrokemypie** [charmbracelet/bubbles#78]
When you disable the help and quit bindings of the list widget, for example with the following:
```
listModel := list.NewModel([]list.Item{}, list.NewDefaultDelegate(), 0, 0)
listModel.SetShowHelp(false)
listModel.DisableQuitKeybindings()

listModel.KeyMap.ShowFullHelp.SetEnabled(false)
listModel.KeyMap.CloseFullHelp.SetEnabled(false)
```

The help and quit bindings get re-enabled by entering and exiting filtering mode.

These bugs are caused by the [updateKeyBindings method](https://github.com/charmbracelet/bubbles/blob/da9248f877c9cd40fb79916d45f4111c9774ba39/list/list.go#L591) setting the bindings to enabled after ending filtering, regardless of their current state.

This bug is annoying if you are handling help and quit bindings yourself, and causes the SetShowHelp and DisableQuitKeybindings methods to not work as they are described in the documentation.

**Comment by muesli** [comment]
Should be fixed by 1d489252fe50b60b50e7b24679e02323441aec51.
