### ISSUE TITLE
List doesn't refresh keybinds when going from 1 page of items to N pages of items.

### ISSUE THREAD

**Issue by Vilsol** [charmbracelet/bubbles#79]
If you start off a list with a single (or 0) pages, and then update the list of items where more than one page is required, the pagination buttons are disabled.

Current workaround is to do this after you update the list of items:

```go
list.SetFilteringEnabled(list.FilteringEnabled())
```

which as the last step refreshes the keybinds.

**Comment by bashbunni** [comment]
Hey @Vilsol 

Could you provide us with an example to reproduce the issue?

**Comment by Vilsol** [comment]
It appears this was fixed in these 2 PR's:

* https://github.com/charmbracelet/bubbles/pull/90
* https://github.com/charmbracelet/bubbles/pull/94

**Comment by bashbunni** [comment]
Ah ok perfect, thanks!
